# encoding: utf-8
require 'addressable/uri'
require 'json'
require 'logger'
require 'hash'
require 'contact-data/options'
require 'contact-data/contact'
require 'contact-data/link'
require 'contact-data/text'
require 'contact-data/fetcher'
require 'contact-data/deprecated'
